//
// Created by Gianni on 23/01/2025.
//

#ifndef OPENGLRENDERINGENGINE_RESOURCE_IMPORTER_HPP
#define OPENGLRENDERINGENGINE_RESOURCE_IMPORTER_HPP

class ResourceImporter
{

};

#endif //OPENGLRENDERINGENGINE_RESOURCE_IMPORTER_HPP
